// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.onlinebookstore.domain;

import com.springsource.roo.onlinebookstore.domain.Shipping;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Shipping_Roo_Configurable {
    
    declare @type: Shipping: @Configurable;
    
}
